Midwest Healthcare Conference Causal Diagram Challenge: Estimating Causal Effects of Glucocorticoids on COVID-19 Survival 
As part of the 4th Midwest Healthcare Conference, we are hosting a Mini Data Challenge, which offers a valuable opportunity for participants to apply cutting-edge causal inference methodologies to real-world data. By focusing on the causal effects of glucocorticoids  on COVID-19 survival, participants contribute to a critical area of research with significant clinical implications. The challenge fosters innovation and emphasizes the importance of rigorous, transparent, and ethical research practices in healthcare. 
Structural Causal Models

Structural causal models (SCMs) are used as a powerful framework for understanding and analyzing cause-and-effect relationships within complex systems. By utilizing directed acyclic graphs (DAGs), the causal structure between variables can be visually and mathematically represented, allowing for the distinction between correlation and causation. The identification of causal pathways, the prediction of outcomes under hypothetical interventions, and the determination of the impact of changes within a system are enabled by this approach.

Challenge Overview

Identifying the causal effects of an intervention is a central task in the health sciences. Structural Causal Models (SCMs) offer a knowledge-driven, transparent, and rigorous approach to reducing biasing correlations when estimating causal effects from observational data. This Causal Diagram challenge aims to optimize the use of SCMs to estimate the causal effects of glucocorticoids on in-hospital survival rates among COVID-19 patients using real-world data.

Challenge Aim
 
The primary goal is to assess how participants can develop SCMs to estimate the causal effects of glucocorticoids on in-hospital survival rates among COVID-19 patients using a large de-identified COVID-19 dataset. This will help evaluate the robustness and transportability of SCMs in replicating results from randomized controlled trials (RCTs) in a real-world setting. 

Challenge Question
 
Challenge Question: Estimate the causal effects of glucocorticoids on the in-hospital survival of COVID-19 patients using a structural causal model and the provided real-world dataset.

Task Description
 
Participants will submit causal diagrams (formally, SCMs) that precisely describe the causal variables relevant to glucocorticoids  and all-cause in-hospital survival. The SCMs will define variables that the participant believes introduce confounding bias that must be handled with adjustment. Each variable should be labeled as adjusted or unadjusted. Participants are encouraged to specify a functional form for each causal relationship in the proposed diagram but may also utilize a tree-based method that does not require specification of the functional form.

Data Source
 
Dataset: ImmPort dataset with accession SDY1662 titled “An Inflammatory Cytokine Signature Predicts Covid-19 Severity And Survival”

The participants are allowed to use only data provided by organizers.

Output

Estimates of the absolute risk difference/reduction for in-hospital all-cause survival with a bootstrapped compatibility interval and calibration metrics for patient-level in-hospital survival predictions.

Participants must also submit documentation (max 3 pages) describing their modeling strategy that would allow the challenge organizers to reproduce their model if needed.

Ethical Considerations and Data Privacy
•	Data Confidentiality: All data is de-identified to ensure patient privacy and participation in the challenge requires acceptance of the User Agreement for the NIAID Immunology Database and Analysis Portal (ImmPort) which can be reviewed at https://docs.immport.org/home/agreement/.
•	Model Transparency: While the structural causal models developed by participants will not be disclosed, the causal effect estimates and compatibility intervals will be shared to maintain transparency.
•	Ethical Compliance: The challenge adheres to ethical standards in data handling and analysis, ensuring the integrity of the research process.


Evaluation Metrics
 
Primary Metrics
1.	Causal Estimate Coverage:
o	Metric Description: Alignment between the causal effect estimates (including confidence or credible intervals) generated by the team's SCM and those reported from high-quality RCTs.
o	Focus: Patients who would have met the RCT eligibility criteria.
o	Importance: Measures the model's ability to replicate findings from rigorous clinical trials.

Secondary Metrics
Participants will also be evaluated based on:
•	The rigor of the analysis showcases participants’ expertise in data analysis techniques. 

•	Creativity and innovation in participants' approach 


•	Clear and concise documentation of participants' work, including explanations of their models and assumptions, which is crucial for reproducibility and understanding.


## Details
Challenge: Utilize Structural Causal Models (SCMs) to reproduce high-
quality randomized controlled trial findings on the treatment of Covid-19 with
steroids or hydroxychloroquine using real world data
• Therapeutic Area: Severe Covid-19
• Motivation: Real world data is often significantly biased. This challenge
tests the hypothesis that SCMs provide a transparent, rigorous approach to
reduce biasing correlations when estimating causal effects from observational data.

• SCMs use directed acyclic graphs (DAGs) to visually and mathematically represent
causal structures between variables.
• They allow for the identification of causal pathways, prediction of outcomes under hypothetical interventions, and determination of the impact of
changes within a system.

• The D-separation algorithm evaluates whether there are association paths present in a causal diagram that can bias the identification the causal effect between the action and
outcome.
• Adjustment of variables can create or destroy d-separation.
• Our platform implements a d-separation algorithm to highlight biasing paths in orange. This visual aid helps users identify confounding and understand the causal structure
of their model.
• A fully adjusted SCM will have no orange arrows, this may not always be possible.

Using d-separation to identify confounding is crucial for identifying causal effects. By
understanding which paths introduce bias, we can make informed decisions about
which variables to adjust for in our analysis.

• We created separate datasets for Steroids and
Hydroxychloroquine trial emulations.
• This allows for focused analysis on each
treatment while maintaining the structure
needed for our pooled logistic regression
approach (specifically addressing eligibility and
treatment exposure censoring issues, see
below).


We transformed the original dataset into a Person-Time dataset. In a Person-Time
dataset, each day of a patient's hospitalization is represented and eligibility criteria,
action/treatment exposure, outcomes, and variables are tracked. For a Pooled Logistic Regression analysis, each Hospital Day creates a new cohort
and eligibility criteria are applied. Patients are tracked for up to 28 Study Days or
censored if 28 Study Days are not available or the patient deviates from the
emulated randomization.


• We generated data for up to 28 days from
emulated randomization (Study Day 0), where
available.
• Missing data was handled using the last
observation carried forward method.
o This approach allows us to maximize the use of
available data, however there are several limitations
with this strategy.

• Feature association and Datatype selection
occur in the Data Sidebar of the cStructure
platform.
• Here, you'll link your model's nodes to specific
features in the dataset and specify their types
(e.g., binary, ordinal, continuous).
• You can use the Data Dictionary and the Data
Profile to help you select the correct features for
each of your causal diagram nodes.

Each
• Adjusted,
• Action, and
• Outcome Node
must be associated with a Feature and a Datatype
prior to Run Estimation
Tips:
• Boolean variables should use Binary Datatype

 Your submitted model must include:
1. A labeled outcome node (associated with the Death feature
as a binary Datatype)
2. A labeled action node (Steroids or Hydroxychloroquine,
associated with the same feature as a binary Datatype)
3. Confounder variables, labeled, with arrows into the
outcome node or the action and outcome nodes (e.g., Age,
associated with the Age feature, with either ordinal or
continuous feature type, arrow into outcome node)
• Some variables have high rates of imbalance/missingness and
that prevent the statistical model from converging à error
• If a graphical model that resolves to the same
statistical formula is submitted by different teams or named
differently by the same team, the previous bootstrap results
will be associated with the team and model name, and the
same results are returned. This ensures consistency and saves
computational resources.

Each causal diagram will be transformed into a statistical model using the pygformula package to estimate the causal effect with the pooled time-person dataset and 500 bootstraps per severity level.